{{- range .Values.servers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  ports:
  - port: {{ .port }}
    targetPort: {{ .port }}
  selector:
    app: {{ .name }}
  type: ClusterIP
 {{- end }}