apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      {{- if .Values.redis.affinity }}
      affinity:
        {{ toYaml .Values.redis.advancedAffinity | nindent 8 }}
      {{- end }}
      containers:
      - name: redis-master
        image: redis/redis-stack-server:7.2.0-v11
        env:
        - name: REDIS_ARGS
          value: '--appendonly yes'
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.redis.storageClass }}
      resources:
        requests:
          storage:  {{ .Values.redis.storage }} 

---        
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      {{- if .Values.redis.affinity }}
      affinity:
        {{ toYaml .Values.redis.advancedAffinity | nindent 8 }}
      {{- end }}
      containers:
      - name: redis-slave
        image: redis/redis-stack-server:7.2.0-v11
        env:
        - name: REDIS_ARGS
          value: '--appendonly yes --replicaof redis-master 6379 --slave-read-only yes'
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.redis.storageClass }}
      resources:
        requests:
          storage:  {{ .Values.redis.storage }} 
