apiVersion: v1
kind: Service
metadata:
  name: backend-server
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "1"
spec:
  type: ClusterIP
  ports:
    - name: backend-server-8081-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: backend-server-8083-8083
      protocol: TCP
      port: 8083
      targetPort: 8083
  sessionAffinity: None
  selector:
    app: backend-server