{{- if .Values.app.imageproxy_server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: imageproxy-server-env
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-1"
data:
  {{ include "imageproxy_server_env" . | nindent 2 }}
{{- end }}