apiVersion: v1
kind: Secret
metadata:
  name: openresty-ssl-certs
  namespace: {{ .Values.app.openresty.namespace }}
  annotations:
    domain: {{ .Values.app.openresty.server_name }}
type: IngressTLS
data:
  tls.crt: {{ .Values.app.openresty.tls_crt | b64enc | quote }}
  tls.key: {{ .Values.app.openresty.tls_key | b64enc | quote }}

---

{{- if .Values.app.openresty.has_extend_tls }}
apiVersion: v1
kind: Secret
metadata:
  name: openresty-extend-ssl-certs
  namespace: {{ .Release.Namespace }}
  labels:  
    app.kubernetes.io/managed-by: Helm
  annotations:
    domain: {{ .Values.app.openresty.extend_tls_data.tls_domain }}
type: IngressTLS
data:
  tls.crt: {{ .Values.app.openresty.extend_tls_data.tls_crt | b64enc | quote }}
  tls.key: {{ .Values.app.openresty.extend_tls_data.tls_key | b64enc | quote }}
{{- end }}
