kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-10"
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"\",\"auth\":\"%s\"}}}" .Values.images.registry .Values.images.username .Values.images.password (printf "%s:%s" .Values.images.username .Values.images.password | b64enc) | b64enc }}
