apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "10"
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080