
version: latest

imagePullSecrets: []

global:
  pxcEnabled: true
  env: 
    MYSQL_DATABASE: apitable

pxc-operator:
  replicaCount: 1

pxc-db:
  allowUnsafeConfigurations: true
  pxc:
    enabled: true
    size: 1
    resources:
      requests:
        memory: "0.5G" # 4G
        cpu: "300m" # 2
    persistence: 
      size: 3Gi
      storageClass: longhorn
    configuration: |
      [mysqld]
      sql_mode=NO_ENGINE_SUBSTITUTION
      sort_buffer_size=2M
      max_connections=1000
      max_allowed_packet=1024M
      log_bin_trust_function_creators=on
      innodb_dedicated_server=on
      innodb_flush_log_at_trx_commit=2
      lower_case_table_names=1
      innodb_redo_log_capacity=8589934592
      [sst]
      xbstream-opts=--decompress
      [xtrabackup]
      compress=lz4
    # advancedAffinity:
    # tolerations:
    backup:
      enabled: false
      pitr:
        enable: false
        storageName: ""
      # pitrStorageName: suggest use local hdd pvc
      # storages: XXXX
      # schedule:
  # #      - name: "sat-night-backup"
  # #        schedule: "0 0 * * 6"
  # #        keep: 3
  # #        storageName: s3-us-west
  #       - name: "daily-backup"
  #         schedule: "0 0 * * *"
  #         keep: 5
  #         storageName: fs-pvc
  proxysql:
    enabled: true
    size: 1
    resources:
      requests:
        memory: 500m
        cpu: 300m
    persistence:
      storageClass: longhorn
      
redis:
  enabled: true
  storageClass: longhorn

rabbitmq:
  enabled: true
  storageClass: longhorn
  
minio:
  enabled: true
  storageClass: longhorn

cron:
  enabled: false

tidb-operator:
  enabled: true
  clusterScoped: false

tidb:
  enabled: true
  # # The deployed cluster topology by default has three PD Pods,
  # three TiKV Pods, and two TiDB Pods. 
  # If the number of Kubernetes cluster nodes is less than three,
  # one PD Pod goes to the Pending state, and neither TiKV Pods nor TiDB Pods are created.
  # When the number of nodes in the Kubernetes cluster is less than three,
  # to start the TiDB cluster,
  # you can reduce the number of PD Pods in the default deployment to 1.
  # For configuration information, see this page:
  # https://github.com/pingcap/tidb-operator/blob/v1.6.0/docs/api-references/docs.md
  cluster:
    version: master
    pd:
      image: pingcap/pd
      replicas: 3
      requests:
        storage: "10Gi"
      # storageClassName: ""
    tikv:
      image: pingcap/tikv
      replicas: 3
      requests:
        storage: "10Gi"
      # storageClassName: ""
    tidb:
      image: pingcap/tidb
      replicas: 2
      requests:
        storage: "15Gi"
      # storageClassName: ""
    initdb:
      enabled: true
      passwordData:
        apitable: cGFzc3dvcmQ=
        root: YXBpdGFibGVAY29t
      passwordSecret: "tidb-secret"

      # InitSqlConfigMapName reference a configmap that provide init-sql,
      # take high precedence than initSql if set
      # initSqlConfigMap: tidb-init-sql
      initSql: "create database apitable;SET GLOBAL SQL_MODE='IGNORE_SPACE,NO_ENGINE_SUBSTITUTION'"
      # permitHost: "localhost"