apiVersion: v1
kind: ConfigMap
metadata:
  name:  init-appdata-env
  namespace: {{.Release.Namespace}}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "{{ if .Values.hooks.removeOnSuccess }}hook-succeeded,{{ end }}before-hook-creation"
    "helm.sh/hook-weight": "-5"
data:
{{- range $key, $val := .Values.initAppData }}
  {{ $key }}: {{ $val | quote }}
{{- end}}


